corporation_name: 有限公司
output: "D:\\work_space\\parking\\output"
input: "D:\\work_space\\parking\\input\\input.xlsx"
name_pool: "C:\\Users\\Lenovo\\name_pool.log"
holiday_per_month: 4
year: 2025
month: 4
